<?php
return [
'applicant_complaint'       => ['type' => 's', 'title' => 'Заявитель жалобы'], 
'strategy'                  => ['type' => 'm', 'title' => 'Стратегия'], 
'state_duty'                => ['type' => 'i', 'title' => 'Госпошлина'], 
'brief_complaint'           => ['type' => 's', 'title' => 'Краткая апелляционная жалоба'], 
'complaint'                 => ['type' => 's', 'title' => 'Апелляционная жалоба'], 
'objections'                => ['type' => 's', 'title' => 'Возражения на апелляционную жалобу'],
'date_filing_complaint'     => ['type' => 'd', 'title' => 'Дата подачи жалобы'],
'date_acceptance_complaint' => ['type' => 'd', 'title' => 'Дата принятия жалобы судом'],
'court_judge'               => ['type' => 's', 'title' => 'Суд, Судья'],
'date_upcoming_case'        => ['type' => 'md', 'title' => 'Дата назначения к слушанию'],
'number_case'               => ['type' => 's', 'title' => 'Номер дела в суде апелляционной инстанции'],
'link'                      => ['type' => 's', 'title' => 'Ссылка на дело в суде апелляционной инстанции'],
'information_case'          => ['type' => 's', 'title' => 'Информация о ходе рассмотрения апелляционной жалобы'],
'result_case'               => ['type' => 's', 'title' => 'Результат рассмотрения апелляционной жалобы'],
'sum_case'                  => ['type' => 'i', 'title' => 'Сумма заявленных требований и удовлетворенных судом'],
'date_production_case'      => ['type' => 'd', 'title' => 'Дата фактического изготовления апелляционного определения'],
'date_receipt_case'         => ['type' => 'd', 'title' => 'Дата получения апелляционного определения'],
'information_progress'      => ['type' => 'm', 'title' => 'Информация о необходимости обжалования апелляционного определения'],
'date_filing_appeal'        => ['type' => 'd', 'title' => 'Дата подачи жалобы'],
'date_acceptance_appeal'    => ['type' => 'd', 'title' => 'Дата принятия жалобы'],
'sum_services'              => ['type' => 'i', 'title' => 'Сумма оказанных юридических услуг'],
];