<?php
return [
'recoverer'                         => ['type' => 's', 'title' => 'Взыскатель'], 
'debtor'                            => ['type' => 's', 'title' => 'Должник'], 
'date_force'                        => ['type' => 'd', 'title' => 'Дата вступления решения в законную силу'],
'time_limit'                        => ['type' => 's', 'title' => 'Срок для предъявления исполнительного листа к исполнению'], 
'sum_case'                          => ['type' => 'i', 'title' => 'Сумма денежных требований'],
'information_mortgaged_property'    => ['type' => 's', 'title' => 'Сведения о заложенном имуществе'],
'strategy'                          => ['type' => 'm', 'title' => 'Стратегия'],
'date_submission_fssp'              => ['type' => 'd', 'title' => 'Дата подачи исполнительного листа в ФССП'],
'date_initiation_fssp'              => ['type' => 'd', 'title' => 'Дата возбуждения исполнительного производства'],
'contact_bailiff'                   => ['type' => 's', 'title' => 'ФИО судебного пристава-исполнителя, контактные данные'],
'link'                              => ['type' => 's', 'title' => 'Ссылка на исполнительное производство на сайте ФССП'],
'information_progress'              => ['type' => 'm', 'title' => 'Информация о ходе исполнительного производства'],
'arrests_bans_encumbrances'         => ['type' => 's', 'title' => 'Аресты, запреты, обременения'],
'date_visit_bailiff'                => ['type' => 'md', 'title' => 'Даты посещения судебного пристава-исполнителя для контроля его действий и уточнения информации'],
'property_valuation'                => ['type' => 's', 'title' => 'Оценка имущества'],
'information_auction'               => ['type' => 'm', 'title' => 'Сведения о торгах, дата'],
'information_auction_result'        => ['type' => 's', 'title' => 'Сведения о результатах проведения торгов'],
'offer_recoverer'                   => ['type' => 's', 'title' => 'Предложение взыскателю оставить имущество за собой'],
'date_transfer_founds'              => ['type' => 'd', 'title' => 'Планируемая дата перечисления денежных средств'],
'information_provision_debt_fssp'   => ['type' => 's', 'title' => 'Информация о предоставлении в ФССП актуальной информации о задолженности, с учетом процентов на день взыскания'],
'date_transfer_founds_recoverer'    => ['type' => 'd', 'title' => 'Дата поступления денежных средств взыскателю'],
'date_completion'                   => ['type' => 'd', 'title' => 'Дата завершения исполнительного производства'],
'date_end_execution'                => ['type' => 'd', 'title' => 'Дата окончания следующей подачи исполнительного листа'],
];