<?php
return [
'name_and_number'               => ['type' => 's', 'title' => 'Название сделки'], 
'parties_to_case'               => ['type' => 's', 'title' => 'Стороны по делу'], 
'who_represent'                 => ['type' => 's', 'title' => 'Кого представляем'], 
'subject_dispute'               => ['type' => 's', 'title' => 'Предмет спора'], 
'deposit'                       => ['type' => 's', 'title' => 'Залог'], 
'strategy'                      => ['type' => 'm', 'title' => 'Стратегия'],
'claim'                         => ['type' => 'm', 'title' => 'Претензия'],
'claim_price'                   => ['type' => 'm', 'title' => 'Цена иска'],
'state_duty'                    => ['type' => 'm', 'title' => 'Госпошлина'],
'date_start'                    => ['type' => 'd', 'title' => 'Дата начала дела'],
'number_case'                   => ['type' => 's', 'title' => 'Номер дела в суде первой инстанции'],
'court_judge'                   => ['type' => 's', 'title' => 'Суд, Судья'],
'link'                          => ['type' => 's', 'title' => 'Ссылка на дело на сайте суда'],
'information_progress'          => ['type' => 'm', 'title' => 'Информация о ходе дела'],
'date_upcoming_case'            => ['type' => 'm', 'title' => 'Дата предстоящего судебного заседания'],
'information_case'              => ['type' => 's', 'title' => 'Информация о наложении обеспечительных мер'],
'current_state_case'            => ['type' => 'm', 'title' => 'Текущее состояние дела'],
'result_case'                   => ['type' => 's', 'title' => 'Результат рассмотрения дела'],
'sum_case'                      => ['type' => 'i', 'title' => 'Сумма заявленных требований и удовлетворенных судом'],
'date_force_case'               => ['type' => 'd', 'title' => 'Дата вступления судебного акта в законную силу'],
'time_limit'                    => ['type' => 's', 'title' => 'Срок на обжалование'],
'date_production_case'          => ['type' => 'd', 'title' => 'Дата фактического изготовления судом решения'],
'date_receipt_case'             => ['type' => 'd', 'title' => 'Дата получения решения'],
'appeal_case'                   => ['type' => 's', 'title' => 'Сведения о необходимости обжалования судебного акта'],
'date_filing_appeal'            => ['type' => 'd', 'title' => 'Дата подачи жалобы'],
'date_acceptance_appeal'        => ['type' => 'd', 'title' => 'Дата принятия жалобы'],
'sum_services'                  => ['type' => 'i', 'title' => 'Сумма оказанных юридических услуг'],
];
