<?php
return ['FI' => [
            'TITLE'                 => ['type' => 'string',     'title' => 'Название сделки'],
            'UF_CRM_1683462809'     => ['type' => 'integer',    'title' => 'Внутренний номер'],
            'UF_CRM_CONAD_CRD091'   => ['type' => 'string',     'title' => 'Номер дела'],
            'UF_CRM_CONAD_CRD130'   => ['type' => 'string',     'title' => 'Истец'],
            'UF_CRM_CONAD_CRD131'   => ['type' => 'string',     'title' => 'Ответчик'],
            'UF_CRM_CONAD_CRD132'   => ['type' => 'string',     'title' => 'Третье лицо'],
            'UF_CRM_CONAD_CRD002'   => ['type' => 'string',     'title' => 'Предмет спора'],
            'UF_CRM_1666170845189'  => ['type' => 'integer',    'title' => 'Залог'],
            'UF_CRM_1686046817804'  => ['type' => 'link',       'title' => 'Стратегия'],
            'UF_CRM_CONAD_CRD003'   => ['type' => 'link',       'title' => 'Претензия'],
            'UF_CRM_1640249453073'  => ['type' => 'money',      'title' => 'Сумма иска'],
            'UF_CRM_CONAD_CRD004'   => ['type' => 'integer',    'title' => 'Госпошлина'],
            'UF_CRM_CONAD_CRD005'   => ['type' => 'link',       'title' => 'Госпошлина. Платежное поручение'],
            'UF_CRM_CONAD_CRD006'   => ['type' => 'date',       'title' => 'Дата оплаты госпошлины'],
            'BEGINDATE'             => ['type' => 'date',       'title' => 'Дата начала дела'],
            'UF_CRM_CONAD_CRD124'   => ['type' => 'string',     'title' => 'Суд'],
            'UF_CRM_CONAD_CRD125'   => ['type' => 'string',     'title' => 'Судья'],
            'UF_CRM_CONAD_CRD122'   => ['type' => 'string',     'title' => 'Ссылка на дело на сайте суда'],
            'UF_CRM_CONAD_CRD135'   => ['type' => 'mstring',    'title' => 'Информация о ходе дела'],
            'UF_CRM_1702719450'     => ['type' => 'date',       'title' => 'Дата предстоящего судебного заседания'],
            'UF_CRM_CONAD_CRD008'   => ['type' => 'string',     'title' => 'Информация о наложении обеспечительных мер'],
            'UF_CRM_CONAD_CRD009'   => ['type' => 'string',     'title' => 'Текущее состояние дела'],
            'UF_CRM_CONAD_CRD010'   => ['type' => 'link',       'title' => 'Результат рассмотрения дела'],
            'UF_CRM_CONAD_CRD011'   => ['type' => 'integer',    'title' => 'Сумма заявленных требований'], 
            'UF_CRM_CONAD_CRD012'   => ['type' => 'integer',    'title' => 'Сумма удовлетворенных судом'],
            'UF_CRM_CONAD_CRD013'   => ['type' => 'date',       'title' => 'Дата вступления судебного акта в законную силу'],
            'UF_CRM_CONAD_CRD014'   => ['type' => 'string',     'title' => 'Срок на обжалование'],
            'UF_CRM_CONAD_CRD015'   => ['type' => 'date',       'title' => 'Дата фактического изготовления судом решения'],
            'UF_CRM_CONAD_CRD016'   => ['type' => 'date',       'title' => 'Дата получения решения'], 
            'UF_CRM_CONAD_CRD017'   => ['type' => 'string',     'title' => 'Сведения о необходимости обжалования судебного акта'],
            'UF_CRM_CONAD_CRD018'   => ['type' => 'date',       'title' => 'Дата подачи жалобы'],
            'UF_CRM_CONAD_CRD019'   => ['type' => 'date',       'title' => 'Дата принятия жалобы'],
            'UF_CRM_CONAD_CRD020'   => ['type' => 'integer',    'title' => 'Сумма оказанных юридических услуг'],
        ],'AI' => [
            'UF_CRM_CONAD_CRD021'   => ['type' => 'string',     'title' => 'Заявитель жалобы'], 
            'UF_CRM_1686046817804'  => ['type' => 'link',       'title' => 'Стратегия'], 
            'UF_CRM_CONAD_CRD022'   => ['type' => 'integer',    'title' => 'Госпошлина'], 
            'UF_CRM_CONAD_CRD023'   => ['type' => 'link',       'title' => 'Госпошлина. Платежное поручение'], 
            'UF_CRM_CONAD_CRD026'   => ['type' => 'string',     'title' => 'Краткая апелляционная жалоба'], 
            'UF_CRM_CONAD_CRD025'   => ['type' => 'string',     'title' => 'Апелляционная жалоба'], 
            'UF_CRM_CONAD_CRD026'   => ['type' => 'string',     'title' => 'Возражения на апелляционную жалобу'], 
            'UF_CRM_CONAD_CRD027'   => ['type' => 'date',       'title' => 'Дата подачи жалобы'], 
            'UF_CRM_CONAD_CRD028'   => ['type' => 'date',       'title' => 'Дата принятия жалобы судом'], 
            'UF_CRM_CONAD_CRD126'   => ['type' => 'string',     'title' => 'Суд'], 
            'UF_CRM_CONAD_CRD127'   => ['type' => 'string',     'title' => 'Судья'], 
            'UF_CRM_CONAD_CRD101'   => ['type' => 'string',     'title' => 'Номер дела в суде апелляционной инстанции'], 
            'UF_CRM_CONAD_CRD133'   => ['type' => 'string',     'title' => 'Ссылка на дело в суде апелляционной инстанции'], 
            'UF_CRM_CONAD_CRD134'   => ['type' => 'mdate',      'title' => 'Дата назначения к слушанию'], 
            'UF_CRM_CONAD_CRD029'   => ['type' => 'mstring',    'title' => 'Информация о ходе рассмотрения апелляционной жалобы'], 
            'UF_CRM_CONAD_CRD030'   => ['type' => 'link',       'title' => 'Результат рассмотрения апелляционной жалобы (определение)'], 
            'UF_CRM_CONAD_CRD031'   => ['type' => 'integer',    'title' => 'Сумма заявленных требований'], 
            'UF_CRM_CONAD_CRD032'   => ['type' => 'integer',    'title' => 'Сумма удовлетворенных судом требований'], 
            'UF_CRM_CONAD_CRD033'   => ['type' => 'date',       'title' => 'Дата фактического изготовления апелляционного определения'], 
            'UF_CRM_CONAD_CRD034'   => ['type' => 'date',       'title' => 'Дата получения апелляционного определения'], 
            'UF_CRM_CONAD_CRD035'   => ['type' => 'select',     'title' => 'Информация о необходимости обжалования апелляционного определения'],  
            'UF_CRM_CONAD_CRD036'   => ['type' => 'integer',    'title' => 'Сумма оказанных юридических услуг'], 
        ],'CI' => [
            'UF_CRM_CONAD_CRD037'   => ['type' => 'string',     'title' => 'Заявитель жалобы'],
            'UF_CRM_1686046817804'  => ['type' => 'link',       'title' => 'Стратегия'],
            'UF_CRM_CONAD_CRD038'   => ['type' => 'integer',      'title' => 'Госпошлина'],
            'UF_CRM_CONAD_CRD039'   => ['type' => 'link',       'title' => 'Госпошлина.Платежное поручение'],
            'UF_CRM_CONAD_CRD040'   => ['type' => 'link',       'title' => 'Кассационная жалоба'],
            'UF_CRM_CONAD_CRD041'   => ['type' => 'link',       'title' => 'Возражения на кассационную жалобу'],
            'UF_CRM_CONAD_CRD128'   => ['type' => 'string',     'title' => 'Суд'],
            'UF_CRM_CONAD_CRD129'   => ['type' => 'string',     'title' => 'Судья'],
            'UF_CRM_CONAD_CRD136'   => ['type' => 'mdate',      'title' => 'Дата назначения к слушанию'],
            'UF_CRM_CONAD_CRD102'   => ['type' => 'string',     'title' => 'Номер дела в суде кассационной инстанции'],
            'UF_CRM_CONAD_CRD137'   => ['type' => 'string',     'title' => 'Ссылка на дело в суде кассационной инстанции'], 
            'UF_CRM_CONAD_CRD042'   => ['type' => 'mstring',    'title' => 'Информация о ходе рассмотрения кассационной жалобы'],
            'UF_CRM_CONAD_CRD043'   => ['type' => 'link',       'title' => 'Результат рассмотрения (решение, определение, постановление)'], 
            'UF_CRM_CONAD_CRD044'   => ['type' => 'integer',    'title' => 'Сумма заявленных требований'],
            'UF_CRM_CONAD_CRD045'   => ['type' => 'integer',    'title' => 'Сумма удовлетворенных судом требований'],
            'UF_CRM_CONAD_CRD046'   => ['type' => 'date',       'title' => 'Дата фактического изготовления судебного акта'],
            'UF_CRM_CONAD_CRD047'   => ['type' => 'date',       'title' => 'Дата получения постановления суда'],
            'UF_CRM_CONAD_CRD048'   => ['type' => 'select',     'title' => 'Информация о дальнейших действиях'],
            'UF_CRM_CONAD_CRD049'   => ['type' => 'integer',    'title' => 'Сумма оказанных юридических услуг'],
        ],'IP' => [
            'UF_CRM_CONAD_CRD050'   => ['type' => 'string',     'title' => 'Взыскатель'],
            'UF_CRM_CONAD_CRD051'   => ['type' => 'string',     'title' => 'Должник'],
            'UF_CRM_CONAD_CRD052'   => ['type' => 'date',       'title' => 'Дата вступления решения в законную силу'],
            'UF_CRM_CONAD_CRD053'   => ['type' => 'date',       'title' => 'Срок для предъявления исполнительного листа к исполнению'],
            'UF_CRM_CONAD_CRD054'   => ['type' => 'integer',    'title' => 'Сумма денежных требований'],
            'UF_CRM_CONAD_CRD055'   => ['type' => 'string',     'title' => 'Сведения о заложенном имуществе'],
            'UF_CRM_1686046817804'  => ['type' => 'link',       'title' => 'Стратегия'],
            'UF_CRM_CONAD_CRD056'   => ['type' => 'date',       'title' => 'Дата подачи исполнительного листа в ФССП'],
            'UF_CRM_CONAD_CRD057'   => ['type' => 'date',       'title' => 'Дата возбуждения исполнительного производства'],
            'UF_CRM_CONAD_CRD058'   => ['type' => 'string',     'title' => 'ФИО судебного пристава-исполнителя, контактные данные'],
            'UF_CRM_CONAD_CRD059'   => ['type' => 'string',     'title' => 'Ссылка на исполнительное производство на сайте ФССП'],
            'UF_CRM_CONAD_CRD060'   => ['type' => 'mstring',    'title' => 'Информация о ходе исполнительного производства'],
            'UF_CRM_CONAD_CRD061'   => ['type' => 'string',     'title' => 'Аресты, запреты, обременения'],
            'UF_CRM_CONAD_CRD062'   => ['type' => 'mdate',      'title' => 'Даты посещения судебного пристава-исполнителя для контроля его действий и уточнения информации'],
            'UF_CRM_1636705135040'  => ['type' => 'integer',    'title' => 'Стоимость имущества'],
            'UF_CRM_CONAD_CRD138'   => ['type' => 'string',     'title' => 'Сведения о торгах, дата'],
            'UF_CRM_CONAD_CRD064'   => ['type' => 'string',     'title' => 'Сведения о результатах проведения торгов'],
            'UF_CRM_CONAD_CRD065'   => ['type' => 'link',       'title' => 'Предложение взыскателю оставить имущество за собой'],
            'UF_CRM_CONAD_CRD066'   => ['type' => 'date',       'title' => 'Планируемая дата перечисления денежных средств'],
            'UF_CRM_CONAD_CRD067'   => ['type' => 'link',       'title' => 'Информация о предоставлении в ФССП актуальной информации о задолженности, с учетом процентов на день взыскания'],
            'UF_CRM_CONAD_CRD139'   => ['type' => 'date',       'title' => 'Дата поступления денежных средств ИП взыскателю'],
            'UF_CRM_CONAD_CRD069'   => ['type' => 'date',       'title' => 'Дата завершения исполнительного производства'],
            'UF_CRM_CONAD_CRD070'   => ['type' => 'date',       'title' => 'Дата окончания следующей подачи исполнительного листа'],
            'UF_CRM_CONAD_CRD071'   => ['type' => 'link',       'title' => 'Основание окончания исполнительного производства'],
            'UF_CRM_CONAD_CRD072'   => ['type' => 'integer',    'title' => 'Сумма оказанных юридических услуг'],
        ],'BR' => [
            'UF_CRM_CONAD_CRD140'   => ['type' => 'string',     'title' => 'Заявитель'],
            'UF_CRM_CONAD_CRD141'   => ['type' => 'string',     'title' => 'Должник'],
            'UF_CRM_CONAD_CRD142'   => ['type' => 'string',     'title' => 'Конкурсный управляющий'],
            'UF_CRM_1686046817804'  => ['type' => 'link',       'title' => 'Стратегия'],
            'UF_CRM_CONAD_CRD073'   => ['type' => 'integer',    'title' => 'Госпошлина'],
            'UF_CRM_CONAD_CRD074'   => ['type' => 'string',     'title' => 'Госпошлина. Платежное поручение'],
            'UF_CRM_1679485736362'  => ['type' => 'integer',    'title' => 'Депозит'],
            'UF_CRM_CONAD_CRD111'   => ['type' => 'string',     'title' => 'Номер дела'],
            'UF_CRM_CONAD_CRD143'   => ['type' => 'string',     'title' => 'Ссылка на дело в суде'],
            
            'STAGE'                 => ['type' => 'string',     'title' => 'Стадия банкротства'],
            
            'UF_CRM_CONAD_CRD075'   => ['type' => 'date',       'title' => 'Дата окончания текущей стадии'],
            'UF_CRM_CONAD_CRD115'   => ['type' => 'string',     'title' => 'Информация о кредиторах'],
            'UF_CRM_1636705135040'  => ['type' => 'integer',    'title' => 'Стоимость имущества'],
            'UF_CRM_1686038365473'  => ['type' => 'string',     'title' => 'Комментарий по имуществу'],
            'UF_CRM_CONAD_CRD076'   => ['type' => 'string',     'title' => 'Информация о банковских счетах должника'],
            'UF_CRM_CONAD_CRD077'   => ['type' => 'string',     'title' => 'Информация о признании сделок/платежей недействительными'],
            'UF_CRM_CONAD_CRD078'   => ['type' => 'string',     'title' => 'Информация об участии финансового управляющего на судебных заседаниях'],
            'UF_CRM_CONAD_CRD079'   => ['type' => 'integer',    'title' => 'Поступление ДС'], 
            'UF_CRM_CONAD_CRD080'   => ['type' => 'date',       'title' => 'Дата поступления ДС'],
            'UF_CRM_CONAD_CRD081'   => ['type' => 'string',     'title' => 'Субсидиарная ответственность'],
            'UF_CRM_CONAD_CRD082'   => ['type' => 'integer',    'title' => 'Оценка имущества должностных лиц'],
            'UF_CRM_CONAD_CRD083'   => ['type' => 'string',     'title' => 'Результат банкротства'],
            'UF_CRM_CONAD_CRD084'   => ['type' => 'integer',    'title' => 'Сумма оказанных юридических услуг'],
        ],'MD' => [
            'UF_CRM_CONAD_CRD085'   => ['type' => 'link',       'title' => 'Процессуальное правопреемство (дата определения АС)'],
            'UF_CRM_1636705135040'  => ['type' => 'integer',    'title' => 'Стоимость имущества'],
            'UF_CRM_1686038365473'  => ['type' => 'string',     'title' => 'Комментарий по имуществу'],
            'UF_CRM_1686046817804'  => ['type' => 'link',       'title' => 'Стратегия'],
            
            'STAGE'                 => ['type' => 'string',     'title' => 'Стадия банкротства'],
            
            'UF_CRM_CONAD_CRD086'   => ['type' => 'string',     'title' => 'Контакт должника'],
            'UF_CRM_CONAD_CRD087'   => ['type' => 'integer',    'title' => 'Расчет дисконта'],
            'UF_CRM_CONAD_CRD144'   => ['type' => 'string',     'title' => 'Рентабельность'],
            'UF_CRM_CONAD_CRD088'   => ['type' => 'mstring',    'title' => 'Отчет о работе'],
        ],'RE' => [
            'UF_CRM_CONAD_CRD089'   => ['type' => 'string',     'title' => 'Причины, по которым возобновляется производство'],
            'UF_CRM_CONAD_CRD090'   => ['type' => 'string',     'title' => 'Инициатор'],
            'UF_CRM_CONAD_CRD145'   => ['type' => 'string',     'title' => 'Стадия возобновления (направление/стадия сделки)'],
            'UF_CRM_1686046817804'  => ['type' => 'link',       'title' => 'Стратегия'],
        ]];